title: Reprator - Default Challange Accepter
description: >  # this means to ignore newlines until "baseurl:"
  Ktor + Postgres + heroku
permalink: ':title/'
baseurl: "/reprator.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vikram Singh
author-img: admin_photo_vikram.jpg # add your photo
about-author: A default destination for issues with # add description
social-twitter: reprator1 # add your Twitter handle
social-github: TheReprator # add your Github handle
social-linkedin: thereprator # add your Linkedin handle
social-email: mr.vikram004@gmail.com # add your Email address

# Disqus
discus-identifier: Reprator # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
